### ISSUE TITLE
[Feature][Future] WinUI: InfoBar control

### ISSUE THREAD

**Issue by chingucoding** [MADE-Apps/legerity#46]
## Description

InfoBar is currently moving towards preview as indicated by [this PR](https://github.com/microsoft/microsoft-ui-xaml/pull/3325).

## How will this benefit you and others?

This will make it easier to deal with the PagerControl in testing.

**Comment by jamesmcroft** [comment]
Added this new control element wrapper and tests as a part of [recent changes](https://github.com/MADE-Apps/legerity/commit/decd6e9d448c2d0dcb39a84894f2b22e96601fe1)

**Comment by chingucoding** [comment]
Awesome, thank you for this update @jamesmcroft !
