### ISSUE TITLE
[Feature] `WindowsAppManagerOptions` to have option to "Wait/retry" for applicaiton to start/attach

### ISSUE THREAD

**Issue by Smurf-IV** [MADE-Apps/legerity#82]
As can be seen by searching the web,
There is a need to "Wait For" a windows application to start (Especially in CPU resource limited CI build machines)

I have found the `ms:waitForAppLaunch` but that is more like a `Pause` and not a wait  / retry for app start.

What I need is either a way to use `WindowsAppManagerOptions` to attach to an already running instance (So thread wait / repeat until style code) can be done

Or for the `WindowsAppManagerOptions` to take a parameter, so when it is performing the attach, it is waiting for the app window to become available

**Comment by jamesmcroft** [comment]
Something that can be investigated! I'll have a look into this and see if I can come up with a sensible solution. 

I think we have similar code in the [`BasePage`](https://github.com/MADE-Apps/legerity/blob/e699e8a0a5e5cb0c0a42a172872aa99f2ad28855/src/Legerity.Core/Pages/BasePage.cs#L195-L199) class that waits for a specific UI element to be shown.

**Comment by jamesmcroft** [comment]
@Smurf-IV apologies for the delay on coming around to this. In the last version of Legerity, we introduced WaitUntil conditions. 

I've updated the `AppManager.StartApp` method to pass through one of these conditions with a timeout and retry options that should help with this.

**Comment by jamesmcroft** [comment]
Closing this issue now as changes have been made to incorporate wait conditions into the Legerity framework. 

If you've any further questions, feel free to reach out in discussions.
