### ISSUE TITLE
[Feature] Please produce a changelog - So that "we" can see _why 0.6.3 is important_

### ISSUE THREAD

**Issue by Smurf-IV** [MADE-Apps/legerity#83]
Nuget package is stating a new version of 0.6.3
- What's in it ?

**Comment by jamesmcroft** [comment]
Apologies for this, the changes in those revisions were additional minor functionality needed to improve building out the Uno Platform libraries. 

I will post a release changelog however so you can see what has been added.

**Comment by jamesmcroft** [comment]
@Smurf-IV you can find the latest release notes from 0.6 to 0.6.4 here (https://github.com/MADE-Apps/legerity/releases/tag/0.6.4)

Looking back at the changes, these should have been a prelease for a minor update to 0.7 as they are feature enhancements rather than fixes.
